name: DarkChronics-Quake
version: 1.0.0-alpha
main: ru.darkchronics.quake.QuakePlugin
depend: [CommandAPI, WorldEdit]
description: Quake minigame for DC minigames server
author: Polyzium
website: https://darkchronics.ru
api-version: '1.21'